[V2] feat: add replica creation after volumes are garbage collected
kubernetes-sigs/azuredisk-csi-driver pull request #1244
Opened 2022-03-25 19:04 UTC by kassarl

**What type of PR is this?**

/kind feature
**What this PR does / why we need it**:
After volumes are garbage collected and attachment capacity opens up on a node, prompts an attempt to create previously failed replicas

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

2022-03-25 22:08 UTC, edreed commented
/ok-to-test

2022-03-26 06:11 UTC, kassarl commented
/retest

2022-03-28 16:25 UTC, sunpa93 requested changes

2022-03-28 21:02 UTC, kassarl commented
/retest

2022-03-28 21:26 UTC, sunpa93 commented on pkg/controller/replica.go
> +			_, err = r.controllerSharedState.azClient.DiskV1beta1().AzVolumeAttachments(r.controllerSharedState.objectNamespace).List(ctx, metav1.ListOptions{LabelSelector: labelSelector.String()})
As this is in a wait loop, stale cache shouldn't be a problem. Cache will eventually be in the right state (i.e. AzVolumeAttachments for the volume all deleted), at which point controller can recreate failed replica attachments.

2022-03-28 21:55 UTC, sunpa93 commented on pkg/controller/replica.go
> +			return false, nil
We should return true if `len(AzVolumeAttachmentList.Items) == 0`

2022-03-30 21:59 UTC, sunpa93 commented on pkg/controller/replica.go
> +			return false, nil
np: we can probably just do `return len(azVolumeAttachmentList.Items) == 0, nil` instead of having a separate if clause for this.

2022-03-31 04:29 UTC, kassarl commented
/retest

2022-03-31 07:09 UTC, kassarl commented
/retest

2022-03-31 07:40 UTC, kassarl commented
/retest

2022-03-31 17:12 UTC, nearora-msft approved these changes

2022-04-01 18:00 UTC, edreed commented
/retest

2022-04-04 16:51 UTC, nearora-msft commented
/retest

2022-04-04 21:51 UTC, nearora-msft commented
/retest

2022-04-18 16:05 UTC, jmclong commented
The check for the stateful set fails because the` AllPod` property is not populated by the `Create` method. This is currently fixed as a part of #1220. 

Additionally, the `NewPod` created by the test will be created with a volume with `VolumeBindingMode` set to `VolumeBindingWaitForFirstConsumer` for the multi-az test. This results in the `PersistentVolume` of the volume of `NewPod` being set to `nil`. The `VerifySuccessfulAzVolumeAttachments` method will see that `PersistentVolume` is `nil` without checking to see if the primary and replica attachments are successful. This causes the expected "failure" to pass and the test to fail for the multi-az case. Other tests change the `VolumeBindingMode` to `VolumeBindingImmediate`, so that may be an option to fix that issue.

Finally, I noticed that the test will fail if you run it multiple times. This is because ./hack/verify_examples.sh is called after the test suite. It creates a stateful set and deployment that are not cleaned up. This won't interfere with the test when running in the cluster, because it runs after the suite, but can be confusing when running the test interactively.

2022-05-05 13:25 UTC, jmclong commented
Hi @edreed,

Please close this pull request, as I do not have write-access to the branch.

I will create a new one, as #1305 has now been merged into main_v2.

Thanks!

2022-05-05 15:27 UTC, edreed commented
This PR will be replaced by a new updated PR from @jmclong .

2022-05-05 15:27 UTC, closed without merging