fix: ensure that readonly is disabled when disks are brought online
kubernetes-sigs/azuredisk-csi-driver pull request #1909
Opened 2023-07-18 14:16 UTC by andyzhangx

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: ensure that readonly is disabled when disks are brought online

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: ensure that readonly is disabled when disks are brought online
```

2023-07-18 23:47 UTC, andyzhangx commented
/test pull-azuredisk-csi-driver-e2e-capz-windows-2019-hostprocess
/test pull-azuredisk-csi-driver-e2e-capz-windows-2022-hostprocess

2023-07-19 02:52 UTC, andyzhangx commented
/test pull-azuredisk-csi-driver-e2e-capz-windows-2019-hostprocess
/test pull-azuredisk-csi-driver-e2e-capz-windows-2022-hostprocess

2023-07-19 14:50 UTC, andyzhangx commented
/test pull-azuredisk-csi-driver-e2e-capz-windows-2019-hostprocess
/test pull-azuredisk-csi-driver-e2e-capz-windows-2022-hostprocess

2023-07-22 02:55 UTC, andyzhangx commented
/test pull-azuredisk-csi-driver-e2e-capz-windows-2019-hostprocess
/test pull-azuredisk-csi-driver-e2e-capz-windows-2022-hostprocess

2023-07-24 11:45 UTC, andyzhangx commented
/test pull-azuredisk-csi-driver-e2e-capz-windows-2019-hostprocess
/test pull-azuredisk-csi-driver-e2e-capz-windows-2022-hostprocess

2023-07-26 11:50 UTC, andyzhangx commented
/retest

2023-07-26 13:46 UTC, andyzhangx commented
/retest

2023-07-27 03:15 UTC, andyzhangx commented
/retest

2023-07-27 08:12 UTC, andyzhangx commented
/retest

2023-07-27 09:35 UTC, andyzhangx commented
/retest

2023-07-27 13:21 UTC, lippertmarkus requested changes

2023-07-27 13:21 UTC, lippertmarkus commented on test/e2e/suite_test.go
> +		// todo: find a way to get the size of the volume on Windows node
`fsutil volume diskfree C:\\mnt\\test-1\\ | Select-String "Total bytes" | Select-String "15.0 GB"`

2023-07-28 06:55 UTC, andyzhangx commented
/retest

2023-07-28 09:42 UTC, andyzhangx commented on test/e2e/suite_test.go
> +		// todo: find a way to get the size of the volume on Windows node
thanks, fixed.

2023-07-28 09:42 UTC, merged

2023-07-28 09:43 UTC, andyzhangx commented
/cherrypick release-1.28